import { Category } from "@prisma/client";

import prisma  from "../lib/prisma";

async function main() {
  await prisma.win.deleteMany({
    where: { isDemo: true },
  });

  await prisma.win.createMany({
    data: [
      {
        title: "Reduced AWS infrastructure costs by 20%",
        category: Category.COST_SAVINGS,
        situation: "Cloud spend had grown steadily as traffic and background jobs increased.",
        task: "Find savings without hurting performance or reliability.",
        action: "Reviewed usage patterns, rightsized services, removed idle resources, and added lifecycle policies.",
        result: "Reduced monthly infrastructure spend while preserving application performance.",
        impactMetric: "20% cost reduction",
        technologies: ["AWS", "CloudWatch", "Terraform"],
        isDemo: true,
      },
      {
        title: "Cut API latency from 450ms to 180ms",
        category: Category.PERFORMANCE,
        situation: "A high-traffic endpoint was slowing down the user dashboard.",
        task: "Improve response times before a major customer rollout.",
        action: "Added database indexes, reduced N+1 queries, and cached expensive lookups.",
        result: "The endpoint became significantly faster and more reliable under load.",
        impactMetric: "60% latency reduction",
        technologies: ["PostgreSQL", "Rails", "Redis"],
        isDemo: true,
      },
      {
        title: "Led a production incident recovery in under one hour",
        category: Category.LEADERSHIP,
        situation: "A production issue caused failed requests during a customer-facing release.",
        task: "Coordinate the response, restore service, and prevent recurrence.",
        action: "Organized debugging, communicated status updates, rolled back the risky change, and documented follow-up work.",
        result: "Service was restored quickly and the team left with a stronger incident process.",
        impactMetric: "45-minute recovery",
        technologies: ["Datadog", "Rails", "PostgreSQL"],
        isDemo: true,
      },
      {
        title: "Eliminated duplicate record creation in checkout flow",
        category: Category.DEBUGGING,
        situation: "Customers occasionally saw duplicate records after retrying failed requests.",
        task: "Find the root cause and make the flow idempotent.",
        action: "Traced request logs, identified a race condition, and added idempotency keys.",
        result: "Duplicate records stopped appearing in production.",
        impactMetric: "0 duplicate incidents over 6 months",
        technologies: ["Rails", "PostgreSQL", "Sidekiq"],
        isDemo: true,
      },
      {
        title: "Refactored legacy code into a service/repository architecture",
        category: Category.ARCHITECTURE,
        situation: "Business logic was scattered across controllers and models.",
        task: "Make the codebase easier to test, extend, and onboard into.",
        action: "Introduced service objects, repositories, validators, and clearer controller boundaries.",
        result: "Feature work became easier to reason about and safer to ship.",
        impactMetric: "30% faster feature delivery",
        technologies: ["Next.js", "TypeScript", "Prisma"],
        isDemo: true,
      },
      {
        title: "Reduced customer-facing support issues by 15%",
        category: Category.RELIABILITY,
        situation: "Recurring bugs were creating avoidable customer support volume.",
        task: "Improve product stability and reduce repeated incidents.",
        action: "Grouped recurring issues, fixed root causes, added regression tests, and improved internal documentation.",
        result: "Customers experienced fewer repeat issues and engineers spent less time firefighting.",
        impactMetric: "15% fewer support issues",
        technologies: ["Rails", "RSpec", "PostgreSQL"],
        isDemo: true,
      },
      {
        title: "Built onboarding workflow that improved activation",
        category: Category.REVENUE,
        situation: "New users were dropping off before completing setup.",
        task: "Reduce friction and help users reach value faster.",
        action: "Simplified setup steps, added validation, and improved progress feedback.",
        result: "More users completed onboarding and reached the product's core workflow.",
        impactMetric: "18% activation lift",
        technologies: ["React", "Rails", "PostgreSQL"],
        isDemo: true,
      },
      {
        title: "Stabilized partner API integration with retries and alerts",
        category: Category.RELIABILITY,
        situation: "A third-party integration intermittently failed and caused delayed processing.",
        task: "Make the integration resilient to temporary failures.",
        action: "Added retry logic, timeout handling, error classification, and alerting.",
        result: "Temporary vendor failures no longer caused silent data loss.",
        impactMetric: "92% fewer failed syncs",
        technologies: ["Node.js", "Queues", "Datadog"],
        isDemo: true,
      },
      {
        title: "Reduced database query time by adding targeted indexes",
        category: Category.PERFORMANCE,
        situation: "A reporting page became slow as the dataset grew.",
        task: "Improve query performance without rewriting the feature.",
        action: "Analyzed query plans, added compound indexes, and removed unnecessary joins.",
        result: "Reports loaded quickly even with larger data volumes.",
        impactMetric: "8s → 900ms query time",
        technologies: ["PostgreSQL", "EXPLAIN", "Prisma"],
        isDemo: true,
      },
      {
        title: "Created CI improvements that saved engineering time",
        category: Category.COST_SAVINGS,
        situation: "Slow builds were delaying pull requests and wasting compute minutes.",
        task: "Reduce build time and CI cost.",
        action: "Cached dependencies, split test jobs, and removed redundant checks.",
        result: "Engineers got feedback faster and CI consumed fewer resources.",
        impactMetric: "35% faster builds",
        technologies: ["GitHub Actions", "Node.js", "TypeScript"],
        isDemo: true,
      },
      {
        title: "Designed a secure role-based access control model",
        category: Category.ARCHITECTURE,
        situation: "Different user types needed access to different product areas.",
        task: "Create a permissions model that was flexible but easy to maintain.",
        action: "Modeled roles, permissions, ownership checks, and route-level authorization.",
        result: "The app supported safer multi-user workflows.",
        impactMetric: "4 user roles supported",
        technologies: ["Next.js", "Auth.js", "Prisma"],
        isDemo: true,
      },
      {
        title: "Fixed memory leak causing worker restarts",
        category: Category.DEBUGGING,
        situation: "Background workers restarted during large processing jobs.",
        task: "Find and fix the memory growth issue.",
        action: "Profiled job execution, found retained objects, and streamed large payloads instead of loading them all at once.",
        result: "Workers handled large jobs without unexpected restarts.",
        impactMetric: "70% lower memory usage",
        technologies: ["Node.js", "Queues", "Profiling"],
        isDemo: true,
      },
      {
        title: "Improved checkout reliability during peak traffic",
        category: Category.RELIABILITY,
        situation: "Traffic spikes increased failed checkout attempts.",
        task: "Keep the checkout flow stable during high load.",
        action: "Added rate limiting, safer retries, and better transaction boundaries.",
        result: "Checkout failures dropped during peak usage windows.",
        impactMetric: "40% fewer failed checkouts",
        technologies: ["Rails", "PostgreSQL", "Redis"],
        isDemo: true,
      },
      {
        title: "Delivered revenue reporting dashboard for leadership",
        category: Category.REVENUE,
        situation: "Business stakeholders lacked visibility into revenue trends.",
        task: "Create a dashboard that surfaced key metrics clearly.",
        action: "Built backend aggregation queries and a frontend dashboard with filters.",
        result: "Leadership could review revenue performance without manual reports.",
        impactMetric: "10 hours/week saved",
        technologies: ["React", "PostgreSQL", "Rails"],
        isDemo: true,
      },
      {
        title: "Mentored junior engineers through production-ready PRs",
        category: Category.LEADERSHIP,
        situation: "New engineers needed support shipping confidently.",
        task: "Help teammates improve code quality and delivery habits.",
        action: "Reviewed PRs, explained tradeoffs, paired on debugging, and documented patterns.",
        result: "Teammates shipped safer changes with fewer review cycles.",
        impactMetric: "25% fewer PR revisions",
        technologies: ["GitHub", "RSpec", "TypeScript"],
        isDemo: true,
      },
      {
        title: "Root-caused intermittent authentication failures",
        category: Category.DEBUGGING,
        situation: "Some users were randomly logged out during active sessions.",
        task: "Identify why sessions were failing intermittently.",
        action: "Compared cookie behavior, token expiry, environment variables, and deployment logs.",
        result: "Authentication became stable across local and production environments.",
        impactMetric: "99.9% successful session validation",
        technologies: ["Auth.js", "Next.js", "Cookies"],
        isDemo: true,
      },
      {
        title: "Introduced background jobs for long-running imports",
        category: Category.ARCHITECTURE,
        situation: "Large imports blocked requests and created timeout risk.",
        task: "Move slow processing out of the request cycle.",
        action: "Created a job pipeline with statuses, retries, and failure tracking.",
        result: "Users could submit imports and continue using the app while processing completed asynchronously.",
        impactMetric: "0 request timeouts",
        technologies: ["Sidekiq", "Redis", "Rails"],
        isDemo: true,
      },
      {
        title: "Prevented deployment regressions with automated tests",
        category: Category.RELIABILITY,
        situation: "Manual QA missed edge cases during releases.",
        task: "Increase confidence before deploying.",
        action: "Added regression specs around critical flows and wired them into CI.",
        result: "Production regressions became less frequent.",
        impactMetric: "50% fewer release bugs",
        technologies: ["RSpec", "GitHub Actions", "Rails"],
        isDemo: true,
      },
      {
        title: "Improved frontend load time by trimming bundle size",
        category: Category.PERFORMANCE,
        situation: "The app felt slow on first load.",
        task: "Improve perceived performance for users.",
        action: "Removed unused dependencies, split heavy components, and deferred non-critical code.",
        result: "Users saw content faster on initial page load.",
        impactMetric: "45% faster first load",
        technologies: ["React", "Next.js", "Bundle Analyzer"],
        isDemo: true,
      },
      {
        title: "Recovered failed payment webhooks safely",
        category: Category.REVENUE,
        situation: "Webhook failures risked missed revenue events.",
        task: "Ensure payment events were processed reliably.",
        action: "Added signature validation, retry handling, event deduplication, and replay tooling.",
        result: "Revenue events became traceable and recoverable.",
        impactMetric: "$120K in protected monthly volume",
        technologies: ["Stripe", "Webhooks", "PostgreSQL"],
        isDemo: true,
      },
      {
        title: "Created shared API validation layer",
        category: Category.ARCHITECTURE,
        situation: "Endpoints handled validation inconsistently.",
        task: "Standardize request validation across the app.",
        action: "Introduced schemas, shared parsing helpers, and consistent error responses.",
        result: "APIs became easier to maintain and safer to extend.",
        impactMetric: "12 endpoints standardized",
        technologies: ["Zod", "TypeScript", "Next.js"],
        isDemo: true,
      },
      {
        title: "Resolved slow admin dashboard caused by N+1 queries",
        category: Category.DEBUGGING,
        situation: "An internal dashboard became unusable with larger customer accounts.",
        task: "Find why performance degraded at scale.",
        action: "Inspected query logs, identified N+1 lookups, and batched related data loading.",
        result: "The dashboard handled large accounts smoothly.",
        impactMetric: "120 queries → 8 queries",
        technologies: ["Rails", "PostgreSQL", "ActiveRecord"],
        isDemo: true,
      },
      {
        title: "Reduced storage costs with lifecycle policies",
        category: Category.COST_SAVINGS,
        situation: "Old uploaded files were stored indefinitely.",
        task: "Lower storage cost while preserving compliance needs.",
        action: "Classified files by age and access pattern, then moved stale files to cheaper storage.",
        result: "Storage spend dropped without removing required data.",
        impactMetric: "28% storage cost reduction",
        technologies: ["S3", "Lifecycle Policies", "AWS"],
        isDemo: true,
      },
      {
        title: "Built observability dashboard for critical workflows",
        category: Category.RELIABILITY,
        situation: "The team lacked clear visibility into critical background processes.",
        task: "Make failures and bottlenecks easier to detect.",
        action: "Created dashboards for success rates, queue depth, errors, and processing time.",
        result: "Incidents were detected earlier and diagnosed faster.",
        impactMetric: "65% faster detection",
        technologies: ["Datadog", "PostgreSQL", "Queues"],
        isDemo: true,
      },
      {
        title: "Shipped customer setup automation",
        category: Category.REVENUE,
        situation: "New customer setup required manual engineering work.",
        task: "Automate repetitive setup tasks.",
        action: "Built forms, validations, and backend workflows to generate required configuration.",
        result: "Customer onboarding became faster and less error-prone.",
        impactMetric: "6 hours saved per customer",
        technologies: ["Rails", "PostgreSQL", "React"],
        isDemo: true,
      },
      {
        title: "Led cross-functional launch with product and support",
        category: Category.LEADERSHIP,
        situation: "A major feature required coordination across engineering, product, and support.",
        task: "Keep launch scope, risks, and communication aligned.",
        action: "Clarified rollout steps, documented support notes, and coordinated release timing.",
        result: "The launch went smoothly with fewer support escalations.",
        impactMetric: "30% fewer launch tickets",
        technologies: ["Jira", "Slack", "Feature Flags"],
        isDemo: true,
      },
      {
        title: "Optimized search with better indexing and filtering",
        category: Category.PERFORMANCE,
        situation: "Users had trouble finding records quickly.",
        task: "Improve search speed and relevance.",
        action: "Added indexed filters, normalized searchable fields, and improved query structure.",
        result: "Search became faster and returned better results.",
        impactMetric: "3.2s → 400ms search time",
        technologies: ["PostgreSQL", "Indexes", "TypeScript"],
        isDemo: true,
      },
      {
        title: "Built safe feature flag rollout process",
        category: Category.RELIABILITY,
        situation: "Large releases created risk because features were all-or-nothing.",
        task: "Enable safer incremental launches.",
        action: "Added feature flags, internal previews, and customer-specific rollout controls.",
        result: "The team could release smaller changes and reduce rollback risk.",
        impactMetric: "75% lower rollback risk",
        technologies: ["Flipper", "Rails", "Feature Flags"],
        isDemo: true,
      },
      {
        title: "Debugged third-party API timeout spike",
        category: Category.DEBUGGING,
        situation: "A vendor integration started timing out unexpectedly.",
        task: "Determine whether the issue was internal, network-related, or vendor-side.",
        action: "Compared request traces, timeout patterns, retry rates, and payload sizes.",
        result: "The team isolated the vendor issue and added safeguards until it was resolved.",
        impactMetric: "88% fewer timeout failures",
        technologies: ["API Logs", "Datadog", "Node.js"],
        isDemo: true,
      },
      {
        title: "Designed audit trail for sensitive user actions",
        category: Category.ARCHITECTURE,
        situation: "The app needed better traceability for important user actions.",
        task: "Create a reliable audit trail without cluttering business logic.",
        action: "Designed event records, metadata capture, and reusable audit helpers.",
        result: "Support and engineering could trace who changed what and when.",
        impactMetric: "100% coverage on critical actions",
        technologies: ["PostgreSQL", "Prisma", "Next.js"],
        isDemo: true,
      },
    ],
  });

  console.log("Seeded 30 demo wins");
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });